// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image6":return img`
1 1 
1 1 
`;
            case "image7":return img`
1 1 1 1 1 1 
1 1 1 1 1 1 
. . 1 1 . . 
. . 1 1 . . 
`;
            case "image8":return img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . . f 1 1 1 1 1 1 f . . . . 
. . . f 1 . 3 3 3 . . 1 f . . . 
. . f 1 . 3 3 3 3 3 3 . 1 f . . 
. . f 1 . 3 3 3 8 8 8 3 1 f . . 
. . f 1 3 3 3 3 8 1 8 3 1 f . . 
. . f 1 3 3 3 3 8 8 3 3 1 f . . 
. . f 1 3 3 3 3 3 3 3 3 1 3 f . 
. f 3 3 1 3 3 3 c c c 1 3 3 3 f 
f 3 3 3 3 1 1 1 1 1 1 3 3 f 3 f 
f 3 f 3 3 3 3 3 3 3 3 3 3 f f . 
. f f 3 3 3 3 3 3 3 3 3 3 f . . 
. . . f 3 3 3 3 3 3 3 3 f . . . 
. . . . f 3 f f f f f 3 3 f . . 
. . . . . f . . . . . f f . . . 
`;
            case "image9":return img`
. 
`;
            case "image10":return img`
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccbcccccccccbccccccccccccccccccccccccccccccbccbcccbccccccccbccccccccbccccccccccccccccccccccbcccccbccccccccccccccccbcccccccccccccccccccccccccccccc
ccbccccccbccccbccccccccccccccccccccccccccccccccccccbcccccccccccccccccccbccccbccccccccccccccccbcccccccccbccccccccccccbccccbcccccccccccccccccccbcccccccbcccbcccccc
cccccccbcccccccccccccccbcccccbccccccbccccccccbccccccccccccccccccccccccccccccccccccccccbcccbccccccbcccccccccccccccccccccccccccccccccccccccccccccccbcccccccccccbcc
cccccccccccccccccccccccccccccccccccbccccbcccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccccccccccbcccccccccbccccbcccccccccccccccccccc
cccccccbcccccbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcccccbccccccccccccccccccccccccccccccccccccccbccccccccccccccccccccccccccbcccccc
ccbccccccccccccccbccccccbccccbcccbcccccbccccccccccccccccccbccccccbccccccccccccccccccccccccccbccccccccccccbcccccccbcccccccbcccccccbcccccccbcccccccccccccccccccbcc
ccccccccccbccccccccccbcccccccccccccccccccbcccbccccbccbccccccccccccccbccccccccbcccccccccccccccccccccccccbccccccccccccccccccccccccccccccbccccccccbbccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcccccccccccbccccccccccccccccccbccccbcccccccccccccbccccccccbccccccccccccccccccccccccccccccbccccccccc
ccccccccccccccccccccbccccccccccccccccccccccccbccccccccccccccccccccccbccccccccccccbcccbccccccccccccccccccbcccbcccbcccccccccccbbcccccccccccccccccccbcccbccccbccccc
ccccccccccbcccbccccbccccbcccccccccccbcccccccccbccccbcccbcccccbbcbcccccccbccccbcccbcccccccbccccccbbccccbccbccccbccccccbccccccccccccccbcccccbcccccccccbcccccccccbc
cccbcccccccccccccccccbcccccccccccccbbcccccccccccbcccccccccbbccccccccccbcccccccccccccccbcccccccbcccccccbcccccccccccccccbcccbcccccbccbccccbccccccccccccccccccbcccb
bcccbcbcbccccccbcccbccccccbcbbccbccccccccbcbccccccccbcccccccccccccbcccccccbccbccccccccccbccccccbcccccccccccccccccccbcccccccbccccccccccbcccccbcbccccbcccccccccccc
ccccbccccccccccbcccccccccccbccccccbccccbcbcccccccccccbccccccccccccbcbccccccccbcccccbcccccccccccccccccccccbcccccccccccccbccccccccccccbccccbcccccccccccccccbcccccc
cbbcbccccccbccccccbccbccccccbcbcccbcccccccccbccbcbcccccccbccccbccbcccbccccbccccccbcccbccbcbcbcccccccccccbccccccccbccbcccccbccccccbbccccccccccbcccccbcbcccccccbcc
ccccccccccccccbcccccbccccccccccccccccccccbcccccccccccccbccccccccccccccccccccccbcccccbcccccccccccccccccbccccccbcccccccccccccbcbcccccccccccccccccbcccbcccbcbccbccc
cccccccccccbccccccbcccccbcccccccccccbcccccccccccbcccccccccbccbcccccccccccbccccccccccccccccccccbcbccbcbccccccccbcccbcccccccccbcccccccccbccbcccccccccccccccccccccc
cbcbcbccbcccccbcccbbcccccccccccbccccccbccbcbcbccccccccccccccbccccbcccccbccccbccccbccccbccccccccccccccccbbccccbcbccccbccccccccbcccbccccccbcccccccccbbccccccccbccc
ccccbcbccbccccccccbcccbccccccbcccbcbccccccccccbbcbbcccbcbcccccbcccccbbccbcbcccccbccccbcccbcbcbccbbcccbcccbccccccccbccbcccccbccbcccccbcccccbccbccccccbccccbbccccc
ccbcccccccccccccccccbcbccbcbccccccbccccccbccccccccbcccccbccccccccbcbccccccccbccccccbcccbccbcccbcccccccccccccccccccbccccccbbcccbccbccccbcbcccccbcbccccccbccbcbbcc
ccccccccbcccbcbccccccccccccbbcccccccbbccccccccccccccbcbcccbcbcccccccccccccbcccbcccccccccccccccbcbcccccbccccbcccbbcccccbccccccccccccbccbccccccbccccccccbccccccccc
cbccccccccccbccccccccccccccccccbbbbcccccccccccbccbccccbccccccbcccccbbccccbcccbcccbccccbbcccccbcccbccbcbcccccccbccccccccccccccccbccbccbccccccbcbcccccccccccccbccc
bcccbbccbcccccccbcbbccccccbcccbccccccbbcccccbccbccccccbccbbccccccccccccccccccbcccbccbccccccbbccbbbccbccccccbcbcccccbbccbcccbcbccccccbcccccccccccbccccbbbccbccccc
ccccccbccccccccbccccbbccbccccccbccccccccccbbccccccbbccccbcccccbcbccccbcbccbcccccccbccccccbccccccccccccccccbcccbcccbbcccccccbcbccccbccbccbccccbccccccccccbcbccccc
cbcccccccbbcccbccccccbcccccbccccccccbccccbccccccccccbccccccccccbccbccccccbcccccbccccccccccbccccccccccccccbccccccccccbccccbccccccccbcccccbccbcccccbbccccccccccbbc
cbcccbccbcccccbccccccccbccbccbcccccbcbccccbccccbccbbbbccccccccccccbccccccbbccccccccbbccbcccccccccbccbcccccccbccbccccccbccbccccccbccbbccccbbcbccccccccccbbbccccbc
bcbccccccccccbcccbbccbcccccbcccbcccbcbccbbccbcbcccccccbccbcbccbccccbcbccccccbcccccbccccbcbbbbccccbccccbbcbbcccccccbcccccccbcbbcbccccbccccbcccccccbbbccbbcccccccb
ccbccbbccbcbbbccbbccbccccbcccbccbcbcbccccbccccbcccbcbcccccbcccccccbccbbcccccbcbccccbccbcccccbbccbccbbcccccbccccbbccbccbbcccccccbccbccccccbccccccccccccbccbccbccc
cccccbccbcccccccccccccbccbccbccccccccbcccccccccccbccccccccbccbbbcccbccbcbbccccbcbccccccccccbccbccccccccccbccbccccccbcccbbccbcccccbcccbcbccccbbbcccbcccccbccccccb
cccbcccbcccccbcbccbcbcccccccbbcccccccbbcbbcccccbccbcccccccccbccccccccccccccccccbbbcccccccccbcbcbccbccbcbccccbcccbccbcbccbccccbbcccbccbcbccccbbccbcccbbcccccccccc
bccbccccbcbcccccccccbccccccbcbbccbcccbcccbcccccbbccccbccccbbccbbbbccbbcbbbcccccccbccbccbccbcccccbcccccbccbcccccbcbcbcccccccbcbcccccbcccccccbbbcccccccbccbccccbcc
ccccccbbbccbcbccbcccbcccbbccccccbccbcccccccbbcccccccbccccbcbcbcccbbcbcccbcbcccbcccccccbbbccccccbcccccccbcccccbbccccccbbcbbccccccccbcccbcccbccccccccccccccbbccbcc
bcccbccccccccccbbcbccbccbcccccccbccccbccccccccbccbcbcbbccccccccccccccccccccccbcbcbccccccccbcbcccbbccccccbcbbcccccccccccbcccccccbccbccbcccbcbccccbcbbcccbcccbcbcb
cbbcccccbcbccccccccccccccccccbccccbccccbbccccccccccbcbbccbbcbcccccccbccccbccccbbbbcbbbccbccbcccccccccccbccccccccbcccbcbccccccccccccbcbbbbccccbbcccbcccbccbbccbcc
cbcccbbcbccccbbccbbcbcccbcbbccbcbcbcccccbcccccbbbbcccbccbbccbccbcbcbccbccbbcbcbbbbccccbcbcbcbbcccbccccccbbccbccccbccbcccccbcccbbbcbbcbccbbcccbcccccbcbcbcbccbcbc
cccbbcbbcccccbbcbbcbcbbcccccccccccccccbbbcccccbcccbcccbcccccbcccccbcbccbcccbccccccccccccccccbbcccbcbbcbccbccccbccbcbccbbbcbccbbcccccccccccbcbccccbbccbccccbccccc
bcccccccbccbbccccccccbcbcbbccbbbbcbcbbcccbbccbcbcccbbcccbcccccbcbbccccbccbccccccccccccbbbcccbccccbcbccbbccbbbbbccbcccccccbcbcccbcbcccccbcbcccccbbcccccbccccbbbcc
bccbcbbcbccccbcccbcccccbccbbbbbbbbbcccbccbccccbcbccbcbbccccbccccccbccbcbbbcccbccbccccbcbbcccbbcccbcbcbccccccbccbccbbcbccbcbcccccbcccccbccbbbbcbbccbbcbcbcccbbbcc
cbbccbbccbbbcccbccbcccbbbbcbccbbbbcccbbcbcbbcbbccbcbcccbbcbccccbbccbcbbcccccbbbbbcbbcccbccccccbccbccbbccbbccbcbccbbcbbcbcccbbcbcccccccbbcccbbcbcbbccbcccbbcccbcc
ccbcccccccbbbcbbcbcbbbccbccccccccccccbccbcccbccccbccbbccccbbbcbbbccccccbcbcbccccbcbccbbbbcbbbbcccbcccbbccbccccbccbcbcccbcccbbbbccbbbcbcccccbcccbcccbcccbcbbccccb
bcccbbcccccccbccbccbccbccccccccccbccbbccccbccbcbbcccccbcccbccbbcbcbccbccbbcccccbcccccccccbbcbcccccbbcccbcbbbccbccccccbcccbcbccbcbccbcbbcbccccccccbcccbbcbcccccbb
cbcbcbcccbbccbcccccbcbbcccccbbbccbbccbcbcbcccbccccbccbbccbccbbcccbcccbccbccbccbccbccbcbbbbbccbccbccccccbbccccbcccbbcbccbbccccbbccbccbbccccbcccccccbbcbcccbcccbcc
cbcccccbccbbcbcccbbcccbccbbccccbccccbcbcbccccbbcbcbbbccccccbbccbcbbbcccbcbcbcccccbcbccbcccbbcccbbbccccbbbcccccbbbbbccccbbbccccccccbbbccccbccccbbcbcbbcbbbbbcbbcc
cbcccbccbcccbcbbccbbccbbbccbcbbcbbcbccbcbbccbccccbccbcccccbcbccbccbccccccccccbbbccbcbbcccbccccbbccccbbccbbcbcccccccbcbbcbcbccbbccbccccbbbcbccbbbccbccccbcbbcbbcc
bcbcbbbccccbcbcccccbcccbbcbcccccbccccccbcbbccbbcccbcbbccbcbbccccbcccbbbbbbccbbccbccbccccccccccbbbbbccbcccccbbbcbccccccbccccbbbccbcbcbccccbcbcccbcbcccbccccccccbc
bbcbccbbcbcccccccbbbccbbcbbccbcbcbccbccccbcccbccbcccbcccbcbcbbcccbbbbbbbbcccbcbbcbbbbbbbcbcbcbbcbbcccbccbbbccbbccbcccbccbcbcbccccbcbbcbbcbbcbcccbcbbccbbcccccbcb
ccbbcbbcbcccbcbbccbcccbccbbccbccbbbbccccbccccbcbcbbcbcbcbbcbcbbbccbccccbbcbccbccccbbcccbcbcbcccbbcbbbcbbbccbbcbcbccbbcccbbbbbbccbcbbbcbccbbcbcbccbccbbccbcbccccb
ccbccbbccbbbccbcbbccbbcccbbcccbbcbcbcbbccbbbbcbcbbcbcbbccbccccbcbccbccbcbcbbbbcbccbbbbccbbccbcbcccbcccbccccccccbcbcbbbbbccccbbbccbccccbccbccbbcccccccbbccbbcbbcc
cbccbcccbccbbbbcccbccbbcccbcbbccccccbbbbcbbccbbccccbcbcbbccccbcccccbcbcccccbcccccccccccccbccbccbbccccbbccbbcbccbcbbcbccccbcccccbccbccccbbccbcbcbcbbbbccccbbbcbbc
cbbcbbcccbcbcbcbcbcbccccbbbbbbcbcbbcbbbccbcccbcbbcccccccbccbcbbccbccccbbbcbbcccbcbccbbccbbccccbcccbbbbbccccccbcbbbbbcbccccbbccbccccbcbccbbbbcbcccbbbbcccbbbcbbcc
bcbccccccccccbbbccbcbcbbcbccccbcbbbccbcbbccbccbbbccbbcbcbbcbcbbccbcbbcccbcbcbbccbbccbbbccccbbccbbccbcbccbbcbbccbcccbcccbcccbccbcccbbbcbccbccbbbcbbbbbbbcccbcbccb
cbcbbccbbbbccbccbbcccbbbcbcccccbcbcbccbcccbbccbcbcbcbbcbcccccccbbcbbcbbcccbcbcbccbbbcccbcbcccbbbccbbbcbcbcbcbcccccccbbcbbbbcccbbbbbcccbccbccbcbcccccbccbbbbcccbb
cccbcbbbbcbcccbcbbcccbccccbcbccbcccccbccbcbcbbccbcbcbcbccbcbccbbcbccccbbbcccccbbbcccccbccbbbcccbbcccccbcccbbbcbcbccbccbbcccbcbbbcccbbbbccccbccbcccccbccccccccbcc
bccbcbbccbcbcbbcccbbccbbbbcbcbccbbcccbbcbbbcbcccbcbcccbbccbbbbcbcbcbcbcbcccbcbccbbcccbcccbbbccbbbbbcbcbbbccbbbbcbbcccbbccbbcbbcbcbccbbbbcbccbcccbcbcccbcbbcccbbc
bbbcccbbbccccbcbbcccccbbbcccbcbbbccbbccbcbbbcbbbccbbcbbcbbbbccbccbcbcbcbbbbbcbbbbcbcbccbcccbcbbcccbbcbcbbbbbcbcccbbbcbcbcbbccccbbbbcbcbcbcbbbbbcccbbbbbcbbbbcbcb
cbbccbbcbcbcbcbbbbbcccbcbccbbccbbcccbbcccbccbcbcccbcbbcccccccbbbbccbcbcbcbbccbbcbbbcbbcbbbcbbcbbcbbcbccccbcccbbbbcccbccbcbccbccbccbbcbccbcbbcbbccbccbcbbcccbcccb
cccbccbbcbbbccbcccbbcbbbcbbcbccbbbcbbcbccccbbccbbbcbbccbcbbcbcccbcbcbbccbccccbbccccbcbcbccbcccbccbcccbbccccbbccccbcbcbcbbcbbbbccccbbbccccccbbcbcbbcbbcccccbcbbcb
ccbccbccbccbbcbccbcccbcbbbbcbccbcbbcbcccbcbbcbccbbcccbbccccbcbbcccbcbbbcbbbcbbbbbbbbbbbcbccccbcbcccbccbbcbcbcbbccbcbbbbbbbbcbcbbcbcbbccbcbbbccbbbbbcbbccbccbcccc
bbbbcbcbccbbbcbcbcbcbbbcccbcccbcccbcbcbbbbbccbbccbcbbcbcbbccccbbbbcbbbcbbcbbbcbcccbcbcbcbbcbbcbbbcbbcccbccbbbbcbccbbcccccbbccccbbccbcbbbcbbcbbcbbbcbbbcbbcbcbbbb
bccccbcbbbcbcbcbbcbcbccccbbcbbccccbbbbbcccccccbbbcbcccbcbcbbcbcbcccccbcccccccccbcccbcbcbbcbbbcccccbbbcbcbbbbcbbcccbbccbccccbbbcbbbcbcbcccbbccbbccbccccbcbbcbbcbb
bbcccbbbcbccbccbcbbbbcbcccbbbbbcbbbcbcccbbcccbbbbccbbcbbbccbbcbcbbbbcccbcbcbcccbbcbccccbcccbcbcbcbbcbbcbcccccccbccbbbcbbbbccccbcbcccbcbccccbcccbbcccbcbcccbcbccc
ccbcbbbcbccbcccbbccbcbbbcbcbbcbbbcbbbcbcbcccbcbbbcbccbbccbcbbbbccccbbbbbccccccbbbbccbbcbbcbbcbbccbcbbbbcbcbccbbbcbcbbbcbbbbcccbbcbbcbcbbbccbcbbcbbccbccbbbcbbbbc
bcbcbcbcbccbbbcbbbccbbcccbcbbcbcccccbcbcbbcbbbbcbbbbccbbbbcbbcccbcbbcccbcbbcbcbbccbbbbbbcccbbbbcccbccbcbbcbbbccbbbbbbbbcccbbbcbbccbbbbccbccbbcbcbbcccbbbcbcbccbc
bbbbcbbcbcbcbcbcbcbbccbbbbcccbbcbbbccbbcbbbbccbbbcbcbcbbbbbbbbbbcbcbcbbcbbbccbbbcbbbcccbcbbcbcbcbbbccbbbbcbccccbcbbccbcccccbccbbcbbbcbbbbbcbbbcbbbbccbbcccbbcbcb
bcbccbbcbbbcbbcbcbcbbbccbbbcccbbbcbbbbbccccbccbcccbcccbbccccccbcbbbccbbcbbbbcbccbbccbcccbbbcbbccbcbbcbccbbcccbbbbcccbcbcbbbcccbbbbcccbccbcbcbcbccbbccbcbbccbbbcb
bcbbbbcbcbcccbbcbbccccbbbbccbcbcbbbcbbbbbcbcbccbbbbbbcccbcbbbccbcbcbccbccbbcbbcbcbcbbcbbcbcccbbbccbbbcbbbbbccccbcccbcbccbcbbbcbcccbbcbbcbbbccbbbbbbbcbcccbbccbbb
bcbccbcbcbbbbcccbcccbbcbbcbcbbbbbccbcbbcbccbbcbcbbbbcbcbcccbcbbbcbbbbbbbbbbbbbcbbbbcbccbbcbbbbcbbbbbbcbbccbcccbccbbbbbbbcbbccbccbccbbccbcbbbbcbcccbcbccbbbbbbbbc
bcbccbcccbbbcbbbbbbbccccbbcbbbccbbbcccbcbbbcbbcbccbcbbcbbcbbbbbcbcbccbbbcbbcccbcccbbccbbbbbbccbccbcccbbbcbbcbbbbbbcbccbcccbbbbbbbbcbccbcccbccbbbccbbcbbbccbccbcb
bccbbcbbbcbccbbbcbcbbbbbcbbccccbccbcbccbbccbbcbcccccbbbcccbbcccbcbcbccbcbcccbccbbccbbcbcccbccbbcccbbcccccbbbbbbccbbcbbcbcbcbbcbcbbccbbbbcbbccbcccbbcbbbcbccbccbc
bcbbbbcbbcccbbbccbbbbbcccbcbbbbcbcccbbccbcbbbbbccbccbbbbbbbbccccbbbbccbbbbcbcbbbbcbccbcbbbcbcccbbbccbcbbbcbccbbbbccbbccbbbcbcbcbccbbccbbcbcbbbbbbbbbbccbbbbcbcbc
bbbbbcbbccbbbccbbbbcbbbbcbbcbbccbbbbbbccbbccbbbbbbbbccbcccbcbcbbbcbbbbcbccbbbbbcbbbbbccbcbbbbbbcbbcbbbbbbbbbbcbbcbcbbbbcbbcbbbbbccbbcbbbbbccbcbcbbcbbcbcbcbccbcb
ccccbcccbbbbbcbccccbccbcbcbcbbcbbbbcccbbcbbcccbcbbbbbbcbcbbcbbcbcccbcbbccbbcbcbbccbbbbbbcbcbbbbbbcbbbcccccbccbcbcbbbcbbbbbcbccbbbccbbbbcbbbbccbbcbcbbbbbbbbbcbbb
cbbbbcbbbbcbcbbbbbbcbcbbbbbbccbbbcbcbbbbbbcbcbbccbccbcbcbbcbbbbbcbcbbbcbbbbcccbccbcbccbbbbcccbbcccbbbcbcbbbccbbcbcbbbccbccbcbcbcbbbbbbcccbbccbbccccbcbbccccbcbbb
ccbbbbbbcbbcbcbbbbcbcbcbbbbccbcccbccbccbcbbbccbbbbcbbcbbccbbbbcbccbccbcbbcbcccbbcbbbcbbcbbbcbbbcbbbbcbcbcbbcbcbcbbbbbcbbbbccbbcbbbbcbcbbbccbcbbcbcbbbbbccbbbcbbb
ccbbbcccbcbccbbbbbbcbbbcbccccbbbbbbbbbbbbcbcbbbbccbbbbbccbbbbccbbbcbbbcbbbbbbbcbbbbbbbbbccbbbbcccbbbbbbbbbbbcbbcbbbccbbbbbbbcbbbbbbbccbbbbcbcbbbbbcbbcbccbbcbbcb
cbbbbcbbbbbcbbcbcbbbbcbbbbbbbbbbcbcbbbbcbbbbbbbbbbbbccbbbcbbbcbbbbcbbcbcbcbccbbbcccccbbcbbbccbbcbcbccbbcbcbcbbbbbcbbcbcbcbbbccbbbbcbcbbccbbbbccbbbcccbcbbbbbcbbc
bbbbcbbbbbbbcbbcbcbcbbbccbbbcbbbbbbbcbbccbbcccbcccbbbbbccbbbcbbbbbbbbbbbbbcbbbbcbbbbbbbcbbcbbbbbbbcccbbbcbbbbbbcbccccbbbcbcbcbbbccbcbbbbbbbcbbbbbbbcbbbbbcbcbcbb
cbbbcbbbbbbbbbbbbbbbbbccbbbbbbbccbbbbbbbbcbbbbbbbbcbbbbbbbbbbcbccccbbbbccccbcbcbbcbbccccbbccccbbbbcbcbbbbbccbbccccbbbbbbbbbbbbcbbbbccbbbccbbccbbcbbbbbcbbbbccbbb
bbcbbccbbbbbbbccbccbbbbbcbbbcbbbccbbbcbcccbccbbbbbbccbbcbbccbbcbbbbbbcbcbbcbbbbbbcbbbbbbbbbbbbbbbbbbbbcbcbbbbbbbbbbccccbcbccbcbcccbbbbbcbbbbbbbbbbccbcbbbcbcbcbb
bbbbbbbcbccbccbcbbbcbbccbbcbbbbbcbbbcbbcbbbbbcbbbbcbcbccbbbcbcbcbcbbbbccbbbbcbbbbbbbcbbbbccbbccccbbcbbbbbcbbcbbbcbbbbbbbcbbbbbbbbbbbcccbbbcbccbbbcbbbbccbcbbcbbc
cccbcbbbcbccbbbbbbccbbcbcccbccbcbbbcbbbcbbcbcbccbbccbbbbcbbcbbbbcbbbbbbbcbbbcbbccbccbbbbbcbbbbbbbcbcbcccbbcbccbbcbbbcbbccbbbbccbbcbcbbbbcbbcbbbcbbbcbbbcbbcbcbbb
bbbcccbcbbbbccbbbbbccbbccbbcbbbcbcbbbbbcbbbcbbbcbcbbcbbbbbcbcbcbbbcbbcbbbbcbcbbbcbbbbcbcbbbbbcbbbcbbcbbbbccbbbbbcbbcbbbccbcbccbccbbbbbcbcbbbbcbbbbbbbbbbbcbbbbbb
bbcbbbbbcbcbbbbbbbbbbcbbcbcbbbbcbbcbcbcbcbbbcbbbbbbbbbcbbcbbbcbbbbbbcccbbbbbbbcbbbbcbbbbcbcbbcbbbbbbbccbbbbcbcbbcbbbbbbbbbbbbbbbccbbbbbbbbbbcbbbbbbccbbbcbcbbcbb
bcbbbbbbbcbbbcbbbbbcbbbbbbbbbcbbbbcbbbbbbcbbbbbccbcbcbbbcbbbbcbbcbcbbbbbbbcbbbbbbbbbbbbbcbcbbcbbbbccbbbcbbbcbbcbbbbbcbbbcbbbbbbbbbbbbccbcbbbbcbbcbbbbbcbbbbbbccb
bbbcbbcbcbbbbbcbcbcbcbbbbbbbcbbbbbbcbbcbcbbbbbbccbbbbcbbbbbcbbbbbbbcbbbbbccbccbbcbbcbccbbbbbcbbbcbbbbbbbbbbbcbbccbbbbcbcbbbccbbbcbbbbcbbbcbccbbbccbbbcbcbbbcbbbc
bcbbbbcbbbbbbcbbcbbccbbbbcbcbbbbbccbcbbbbbbbccbbcbbbbbcbcbbbcbbbbcbbcbbbbbbcbbcbcbccbbbbbbcbbbcccbbbccbcbbcbcbbbbbbbccbcbbcccbbcbcbcbbbcbbcbccbbbbbccbcbcbbbbcbc
cbbbcbbbbcbbbbcbbbbbbbbbbbbbcccbbbbbbbbbbccbbbbbbcbbbbcccbbbbbbbcbbbcbbbbbcbbbbbbbcbbbbbbbbbbbbbbbbbbbbcccbcbbcbbbbbbbbbbbcbbbbbbcbbbbbbbccbbbcbbbbbbbbbbbbbbbbb
bbccbbbccbcbcbcbbbbbcbcccbcbbbbbbcbbcbcbbbcbcbbbbbbbbbbcbbbbbbcbbbbbbbbbcbbbcbbbbbbbcbcbbbbbbbbcccbbbbbbbbbbbbbccbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbcbccbbcbbcbbccbb
bbbbbbbccbbbbbbbcbcbbbbbbbbbbcbbcbbbcbbbbbbccbbbccbbbbbbbbccccbbccbbbccbbcbbbcbcbbbbcbcbccbcbbcbcbbbbbbbbbbbbbcbbcbcbbbbbbbcccbbbbbccbccbbcbcbbbbbbbbcbbcbbcbbbb
bcbbbcbccbbbbcbbbcbbbbbbbcbbbbbbbbbcbbbbbbcbbbbcbbbcbcbbbbbbbbbcbbbccbbbbbbcbcbbbbbbbbbbbbbccbbbbbbbbbbcbbccbbbbcbcbbbbbbbbbbbbcbbbccbbbbbbcbcbbbcbbbbcbcbbcbbcb
bbcbbbbbbbbccbbbbbbcbcbbbccbbbbcbbbbbbbbbbbcbbcbbbbbbbbbbcbbbbbbbbbbbbbbcbbbbbcbbbcbbbbbbcbbbbbcbbbcbbbcbbbbbbbbbbbbbbcbbbbcbbbbbbbbbbcbbbbbbbbbbbcbbbbbbcbbbcbb
bbbbbbbbcbbbbbbbbbbbbbcbbbbbbbcbbcbbbbcbbbbbbbbcbbbbbbbbbbbcbbcbbcbbbbbcbcbbbbbcbbbbbbbcbbbbbbbbbbbcbbbbbbbbcbbbbbbbbbbbbcbbbcbbcbbbbbbccbcbbbbcbbbbbbbbbbbbbcbb
bbbcbbcbbbbbbbbcbbbcbcbbbbbbcbbbbbcbbcbcbbbcbbbbccbbcbcbbbcbcbbbbbbcbcbbbbbbbbbbbccbbcbccbbbbbbcbbbccbbbcbbbbbccbcbbbccbbbcbbcbbcbbbbbbbbbbbbbbccbbbccbbbbbbbbbb
bbcbbbbbbcbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbcbcbcbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbcbbbbbbbbbbbbbbbbbbcbcbbcbbbbbbcbbbcbbbcbbbbbccbbbbbbbbbcbbbbbbbbbbcbbbcbbbc
bbbbcbbbcbbbbbbbbbbbbcbcbcbccbbbbbbbbbccbccbbbbbbbcbcbbbbcbbcbbbbbbbccbbbcbbcbbbbbcbbbbbbbbbbbbbbbcbcbbbbbbbbbbbcbbbbbcbbcbbbcbbbbbbbbcbbbcbbbbbbbcbbbcbbbbbcbbb
bbbcbcbbbbcbbbcbbcbcbbbbbbbcbcbbbbcbcbbbbbcbbbbbbbbbbcbbbbbcbcbcbbcbbbbbbbcbcbbbbccbbbbbbbccbcbbbcbbbbbbbbbbcbbbbbbbbbbbbbbbbbcbbbbbcbbbbbbcbbbbbbbbbbbcbcbbbbbb
cbbbbbbcbbbbcbcbbbbccbbbbbbbbbcbbbbcbbbbbbbbbbcbcbbbbbbcbbbcbbbbccbbbbcbbbbcbbbbbbbbcbbcbbcbbcbcbbbcbbcbbcbcbcbbcbbbbcbbbbbcbcbbbcbbbbbcbbbccbbcbcbcbbbbbbbccbbb
bbbcbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbcbbbcbbbbcbbcbbbbbbcbbbbbbcbbbbbbcbbbbbbbcbbbbbbbbbbbbcbbbbbcbbcbbcbbbcbbcbbbbbbcbcbbbbbbbbbcbcbbcbbbbbbb
bbbbbbbbbbcbbcbbbbcbbbbbbcbbbbcbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbcbbbbbbbccbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbcbbbbbbbbbbbbbcbbbbb
bbbbbcbcbbbbbbbcbbbbcbbcbbcbcbbbcbbbbbbbbbbbbbbbbbbcbbbbbbbcbbbbbbbbbbbbbcbbbcbbbcbbbbbbbbbbbcbbbbbbcbbbbbbbbbbcbbbbbbbbbbcbbbbcbbbbbbbbbbbbcbbbbbbbbcbbbbbbbbbc
bcbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbccbbbbbccbcbbcbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbcbcbbcbbbbbccbbbbbbbcbbcbbbbcbbbcbbbbbbbbbbbbbbccbbbbbbbbbbbbbbcbbbbbbbbbbbc
bcbbbbbbcbbbbbcbbbbbbbbbbbccbbbbbbbbbbcccbbbbbcbbbbbbbcbbbbcbbcbbbbbbbbbbbbbcbbbbcbcbbbcbbbbbbcbbbbbbbbbbbbbbbbcbbcbbbbcbbbbbcbcbbbbbbbbbcbbbbbcbbbbbbcbbbbbccbb
bbbcbbcbbbbbcbbbbbbbbbcbbbbbbbbbbbbcbbbbbbbbcbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbcbbbbbbbbbbccbbbbbbbbbbbbcbbbbbcbbbbbbbbbbcbcbbbbbbbbbbbbbbbbbbbbcbbbbbb
bbbbbbbbcbbbbbbbbbbcbbbbbbbbbccbcbbbbbbbbbbcbbbbbbbcbbbbbcbbbcbbcbbbbcbbbcbbbbbbbbbbbbbbcbbbbcbbbbbbbbbbcbbcbbbbbbbbbbbbbbcbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbcbbbb
bbbbbbbcbbbbbbbbbcbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbcbbbccbbbbbbbbbbbbbbcbbbbbbbbbbbcbbcbbbbbbbcbbbbbbbbbbbcbbbbbbbbbcbbbbbbcbbbccbcbbbcbbbbbbbbb
bbbbbbbbbbbbbbbcbbbbcbbbbcbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbcbcbbbbbbbbbbbcbbbcbbbbbbbbbbbbbcbbcbbbbbbbbbcbbbcbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbcbbbbbcbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbcbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbb
bbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbcbbbbbbbbcbbbbbbbbbbbbbbbbbbcbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbb
bbbbbbcbbbcbbbbbcbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbcbbbbcbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbcbbbbbbbbbbcbbbbbbbbbbbbbc
bbbcbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbcbbbbbcbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbcbbbbbbcbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbb
bbbbbcbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbcbbbbbbbbcbbbbbbbbbbbbccbbbbcbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbcbbbbbbccbbbbbbbbbbbbbbbbbbbcbbbbbbbbbcbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbcbbbcbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbcbbbbbbbbcbbbbbbbbbcbbbbbbcbbbbbbbbbbbbbbbcbcbbbbbbbbbcbbbbbbbbbbbbbcbbb
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
